name: "update quickjs"
description: "update quickjs, precompile it, then commit it to the `prebuilt` branch."

on:
  schedule:
    # run daily at midnight
    - cron: "0 0 * * *"
  # allow for manual trigger
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check-and-update:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: true
          fetch-depth: 0

      - name: "detect quickjs submodule update"
        id: detect
        uses: "./.github/actions/check-quickjs"

      - name: "precompile quickjs and commit if changed"
        if: "steps.detect.outputs.changed == 'true'"
        uses: "./.github/actions/compile-quickjs"
